config/routes.rb
Rails.application.routes.draw do
  resources :folders
  get 'browse/:folder_id' => 'home#browse', :as => 'browse'
  get 'browse/:folder_id/new_folder' => 'folders#new', :as => 'new_sub_folder'
  get 'browse/:folder_id/new_file' => 'uploads#new', :as => 'new_sub_file'
  get 'browse/:folder_id/rename' => 'folders#edit', :as => 'rename_folder'
  mount FileUploader::UploadEndpoint => '/files/upload'
  resources :uploads
  post '/json_upload' => 'uploads#json_upload', format: :json
  devise_for :users
  root 'home#index'
end

app/models/folder.rb
class Folder < ActiveRecord::Base
	acts_as_tree
	belongs_to :user
	has_many :uploads, dependent: :destroy
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :update, :destroy]

  # GET /folders
  # GET /folders.json
  def index
    @folders = current_user.folders.all
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
  end

  # GET /folders/new
  def new
     @folder = current_user.folders.build     
     #if there is "folder_id" param, we know that we are under a folder, thus, we will essentially create a subfolder 
     if params[:folder_id] #if we want to create a folder inside another folder 
         
       #we still need to set the @current_folder to make the buttons working fine 
       @current_folder = current_user.folders.find(params[:folder_id]) 
         
       #then we make sure the folder we are creating has a parent folder which is the @current_folder 
       @folder.parent_id = @current_folder.id 
     end
  end

  # GET /folders/1/edit
  def edit
    @folder = current_user.folders.find(params[:folder_id])
    @current_folder = @folder.parent
  end

  # POST /folders
  # POST /folders.json
  def create 
     @folder = current_user.folders.build(folder_params) 
     if @folder.save 
      flash[:notice] = "Successfully created folder."
        
      if @folder.parent #checking if we have a parent folder on this one 
        redirect_to browse_path(@folder.parent)  #then we redirect to the parent folder 
      else
        redirect_to root_url #if not, redirect back to home page 
      end
     else
      render 'new'
     end
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    if @folder.update(folder_params)
      flash[:notice] = "Successfully Updated Folder Name."
      if @folder.parent #checking if we have a parent folder on this one
        redirect_to browse_path(@folder.parent)  #then we redirect to the parent folder
      else
        redirect_to root_url #if not, redirect back to home page
      end
    else
      render 'edit'
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy 
    @folder = current_user.folders.find(params[:id]) 
    @parent_folder = @folder.parent #grabbing the parent folder 

    #this will destroy the folder along with all the contents inside 
    #sub folders will also be deleted too as well as all files inside 
    @folder.destroy 
    flash[:notice] = "Successfully deleted the folder and all the contents inside."

    #redirect to a relevant path depending on the parent folder 
    if @parent_folder
      redirect_to browse_path(@parent_folder)
    else
      redirect_to root_url   
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = current_user.folders.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folder_params
      params.require(:folder).permit(:name, :parent_id, :user_id)
    end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_form.html.haml
= form_for(@folder) do |f|
  - if @folder.errors.any?
    #error_explanation
      %h2
        = pluralize(@folder.errors.count, "error")
        prohibited this folder from being saved:
      %ul
        - @folder.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :name
    %br/
    = f.text_field :name, class: 'form-control', autofocus: true
  = f.hidden_field :parent_id
  .form-group
    - if @folder.new_record?
      = f.button 'Create Folder', class: 'btn btn-primary', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Creating Folder..."}
    - else
      = f.button 'Rename Folder', class: 'btn btn-primary', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Renaming Folder..."}

app/views/folders/edit.html.haml
= render 'home/breadcrumbs'
= render 'form'
%p
  - if @folder.parent
    = link_to "Back to '#{@folder.parent.name}' Folder", browse_path(@folder.parent)
  - else
    = link_to "Back", root_url

app/views/folders/index.html.haml
%p#notice= notice
%h1 Listing Folders
%table
  %thead
    %tr
      %th Name
      %th Parent
      %th User
      %th{:colspan => "3"}
  %tbody
    - @folders.each do |folder|
      %tr
        %td= folder.name
        %td= folder.parent_id
        %td= folder.user_id
        %td= link_to 'Show', folder
        %td= link_to 'Edit', edit_folder_path(folder)
        %td= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Folder', new_folder_path

app/views/folders/new.html.haml
%h1 New Folder
= render 'form'
%p
  - if @folder.parent
    = link_to "Back to '#{@folder.parent.name}' Folder", browse_path(@folder.parent)
  - else
    = link_to "Back to Home page", root_url

app/views/folders/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @folder.name
%p
  %strong Parent:
  = @folder.parent_id
%p
  %strong User:
  = @folder.user_id
= link_to 'Edit', edit_folder_path(@folder)
|
= link_to 'Back', folders_path