config/routes.rb
Rails.application.routes.draw do
  resources :folders
  get 'browse/:folder_id' => 'home#browse', :as => 'browse'
  get 'browse/:folder_id/new_folder' => 'folders#new', :as => 'new_sub_folder'
  get 'browse/:folder_id/new_file' => 'uploads#new', :as => 'new_sub_file'
  get 'browse/:folder_id/rename' => 'folders#edit', :as => 'rename_folder'
  mount FileUploader::UploadEndpoint => '/files/upload'
  resources :uploads
  post '/json_upload' => 'uploads#json_upload', format: :json
  devise_for :users
  root 'home#index'
end

app/controllers/home_controller.rb
# Home Controller Class
class HomeController < ApplicationController
  def index
  	if user_signed_in?
  		@folders = current_user.folders.where("parent_id is null").order('name desc')
      @uploads = current_user.uploads.where('folder_id IS NULL').order('created_at desc')
 	  end
  end

  def browse
    #get the folders owned/created by the current_user
    @current_folder = current_user.folders.find(params[:folder_id])

    if @current_folder

      #getting the folders which are inside this @current_folder
      @folders = @current_folder.children

      #We need to fix this to show files under a specific folder if we are viewing that folder
      @uploads = @current_folder.uploads.sort_by {|u| u.file_name }

      render :action => "index"
    else
      flash[:error] = "No! No! No! That folder doesn't belong to you"
      redirect_to root_url
    end
	end
end

app/views/home/_breadcrumbs.html.haml
.breadcrumbs
  - if @current_folder #checking if we are under any folder
    = link_to "DropBox", root_url
    - @current_folder.ancestors.reverse.each do |folder|
      » #{link_to folder.name, browse_path(folder)}
    »  #{@current_folder.name}
  - else #if we are not under any folder
    DropBox

app/views/home/index.html.haml
- unless user_signed_in?
  %h1 Welcome to ShareBox
  %p File sharing web application you can't ignore.
- else
  #menu
    %ul#top_menu
      - if @current_folder
        %li= link_to "Upload", new_sub_file_path(@current_folder)
        %li= link_to "New Folder", new_sub_folder_path(@current_folder)
      - else
        %li= link_to "Upload", new_upload_path
        %li= link_to "New Folder", new_folder_path
  = render 'breadcrumbs'
  .asset_list_header
    .file_name_header File Name
    .file_size_header Size
    .file_last_updated_header Modified
  .asset_list
    / Listing Folders
    - @folders.each do |folder|
      .asset_details.folder
        .file_name
          %i.fa.fa-folder-o{"aria-hidden" => "true"}
          = link_to folder.name, browse_path(folder)
        .file_size -
        .file_last_updated -
        .actions
          .share
            = link_to "Share"
          .rename
            = link_to "Rename", rename_folder_path(folder)
          .delete
            = link_to "Delete", folder, data: {confirm: 'Are you sure to delete the folder and all of its contents?'}, method: :delete
    / Listing Files
    - @uploads.each do |upload|
      .asset_details.file
        .file_name
          %i.fa.fa-file-o{"aria-hidden" => "true"}
          = link_to upload.file_name, upload_path(upload)
        .file_size= number_to_human_size(upload.upload.metadata["size"])
        .file_last_updated
          = time_ago_in_words(upload.updated_at)
          ago
        .actions
          .download
            = link_to "Download", upload.upload_url, download: upload.upload_url
          .delete
            = link_to "Delete", upload, data: {confirm: 'Are you sure?'}, method: :delete