config/routes.rb
Rails.application.routes.draw do
  resources :folders
  get 'browse/:folder_id' => 'home#browse', :as => 'browse'
  get 'browse/:folder_id/new_folder' => 'folders#new', :as => 'new_sub_folder'
  get 'browse/:folder_id/new_file' => 'uploads#new', :as => 'new_sub_file'
  get 'browse/:folder_id/rename' => 'folders#edit', :as => 'rename_folder'
  mount FileUploader::UploadEndpoint => '/files/upload'
  resources :uploads
  post '/json_upload' => 'uploads#json_upload', format: :json
  devise_for :users
  root 'home#index'
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	include FileUploader[:upload]
	belongs_to :uploadable, polymorphic: true
	belongs_to :user
	belongs_to :folder

	def file_name
		if upload.metadata["filename"]
			upload.metadata["filename"]
		else
			'untitled'
		end
	end

	def download_file
		upload.download
	end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = current_user.uploads.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  def json_upload
    binding.pry
    @upload = Upload.create(params[:upload][:upload])
  end

  # GET /uploads/new
  def new
    @upload = current_user.uploads.build
    if params[:folder_id] #if we want to upload a file inside another folder
      @current_folder = current_user.folders.find(params[:folder_id]) 
      @upload.folder_id = @current_folder.id
    end
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = current_user.uploads.build(upload_params)
    if @upload.save 
      flash[:notice] = "Successfully uploaded the file."
      if @upload.folder #checking if we have a parent folder for this file 
        redirect_to browse_path(@upload.folder)  #then we redirect to the parent folder 
      else
        redirect_to root_url 
      end      
    else
     render 'new'
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload = current_user.uploads.find(params[:id]) 
    @parent_folder = @upload.folder #grabbing the parent folder before deleting the record 
    @upload.destroy 
    flash[:notice] = "Successfully deleted the file."
    
    #redirect to a relevant path depending on the parent folder 
    if @parent_folder
     redirect_to browse_path(@parent_folder) 
    else
     redirect_to root_url 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = current_user.uploads.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:upload, :user_id, :folder_id)
    end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.haml
.panel.panel-default.devise-bs
  .panel-heading
    %h4 Upload Your Files
  .panel-body
    = form_for(@upload, html: { role: 'form', multipart: true }) do |f|
      - if @upload.errors.any?
        #error_explanation
          %h2
            = pluralize(@upload.errors.count, "error")
            prohibited this upload from being saved:
          %ul
            - @upload.errors.full_messages.each do |message|
              %li= message
      .form-group
        = f.hidden_field :user_id, value: @current_user.id
        = f.hidden_field :folder_id
        = image_tag f.object.upload_url, class: 'rounded mx-auto d-block' if f.object.upload_url
        = f.file_field :upload, class: 'form-control'
      .form-group
        = f.button 'Upload', class: 'btn btn-primary', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Uploading..."}

app/views/uploads/edit.html.haml
= render 'form'
= link_to 'Show', @upload
|
= link_to 'Back', uploads_path

app/views/uploads/index.html.haml
%h1 Listing Uploads
%table
  %thead
    %tr
      %th Upload data
      %th User
      %th{:colspan => "3"}
  %tbody
    - @uploads.each do |upload|
      %tr
        %td= image_tag upload.upload_url, class: 'rounded image-dimensions'
        %td= upload.user.name || upload.user.email
        %td= link_to 'Show', upload
        %td= link_to 'Edit', edit_upload_path(upload)
        %td= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Upload', new_upload_path, class: 'btn btn-secondary'

app/views/uploads/new.html.haml
= render 'home/breadcrumbs'
= render 'form'
%p
  - if @upload.folder
    = link_to "Back to #{@upload.folder.name} Folder", browse_path(@upload.folder), class: 'btn btn-secondary btn-xs'
  - else
    = link_to "Back", root_url, class: 'btn btn-secondary btn-xs'

app/views/uploads/show.html.haml
= image_tag @upload.upload_url, class: 'rounded mx-auto d-block'
%br/
%p.text-center= @upload.file_name
%p
  %strong Uploaded By:
  = @upload.user.name || @upload.user.email
= link_to 'Edit', edit_upload_path(@upload)
|
= link_to 'Back', uploads_path